version: '3.8'

services:
  domina:
    container_name: domina
    image: domina
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 9229:9229
    networks:
      - domina-net
    volumes:
      - .:/app
      - domina:/app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: mongod --port 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db
    networks:
      - domina-net

volumes:
  domina:
  mongodb:

networks:
  domina-net:
    name: domina-net
